name: Docker Image CI

on:
  push:
    branches: [ docker-initialization ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v1.6.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: hawful/the-contract
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v2.1.0
      with:
        # List of tags
        tags: hawful/the-contract:latest
