name: Docker Image CI

on:
  push:
    branches: [ docker-initialization ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/setup-buildx-action@v1
      name: Set up Docker Buildx

    - uses: docker/login-action@v1.6.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2.1.0
      with:
        tags: hawful/the-contract:latest
        push: true
